AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  events-and-workflows

  Sample SAM Template for events-and-workflows
  
Globals:
  Function:
    Timeout: 10

Resources:

  ### Inventory

  OrderTable: # customerId, orderId, status (CREATED, RESERVED, PAID, DELIVERING, DELIVERED, CANCELED), itemId, itemPrice, deliveryPrice, totalPrice, paymentId, deliveryAddress, orderDate (timestamp), updateDate (timestamp)
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: "customerId"
          AttributeType: "S"
        - AttributeName: "orderId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "customerId"
          KeyType: "HASH"
        - AttributeName: "orderId" # Timestamp with ms precision
          KeyType: "RANGE"

  InventoryTable: # itemId, description, image (S3 URL in the format “s3://…”), price, available, reserved
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: "itemId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "itemId"
          KeyType: "HASH"

  InventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: inventory/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          INVENTORY_TABLE: !Ref InventoryTable
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:PartiQLSelect
              - dynamodb:PartiQLInsert
              - dynamodb:PartiQLUpdate
              - dynamodb:PartiQLDelete
            Resource: !GetAtt InventoryTable.Arn
      Events:
        InventoryGet:
          Type: HttpApi
          Properties:
            Path: /inventory/{action}/{itemId}
            Method: GET
        InventoryPost:
          Type: HttpApi
          Properties:
            Path: /inventory/{action}
            Method: POST

  ### Payment

  PaymentTable: # paymentId, paymentMethod (CREDIT_CARD for all in this simulation), amount, status (PAID, CANCELED)
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: "paymentId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "paymentId"
          KeyType: "HASH"

  PaymentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: payment/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          PAYMENT_TABLE: !Ref PaymentTable
          PAYMENT_FAIL_PROBABILITY: 0.2 # Between 0 and 1
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:PartiQLSelect
              - dynamodb:PartiQLInsert
              - dynamodb:PartiQLUpdate
              - dynamodb:PartiQLDelete
            Resource: !GetAtt PaymentTable.Arn
      Events:
        PaymentGet:
          Type: HttpApi
          Properties:
            Path: /payment/{action}/{what}
            Method: GET
        PaymentPost:
          Type: HttpApi
          Properties:
            Path: /payment/{action}
            Method: POST

  ### Customer

  CustomerTable: # customerId, name, address (single field for simplicity, includes zip code, town, and state/country), email
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: "customerId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "customerId"
          KeyType: "HASH"

  CustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: customer/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          CUSTOMER_TABLE: !Ref CustomerTable
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:PartiQLSelect
            Resource: !GetAtt CustomerTable.Arn
      Events:
        CustomerGet:
          Type: HttpApi
          Properties:
            Path: /customer/{action}/{customerId}
            Method: GET
        CustomerPost:
          Type: HttpApi
          Properties:
            Path: /customer/{action}
            Method: POST

  # Delivery

  MyPlaceIndex:
    Type: AWS::Location::PlaceIndex
    Properties: 
      IndexName: my-place-index
      DataSource: Esri
      PricingPlan: RequestBasedUsage

  MyRouteCalculator:
    Type: AWS::Location::RouteCalculator
    Properties: 
      CalculatorName: my-route-calculator
      DataSource: Esri
      PricingPlan: RequestBasedUsage
  
  DeliveryTable: # customerId, orderId, address, status (CREATED, DELIVERING, DELIVERED, CANCELED)
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: "customerId"
          AttributeType: "S"
        - AttributeName: "orderId"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "customerId"
          KeyType: "HASH"
        - AttributeName: "orderId" # Timestamp with ms precision
          KeyType: "RANGE"

  DeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: delivery/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          PLACE_INDEX: !Ref MyPlaceIndex
          ROUTE_CALCULATOR: !Ref MyRouteCalculator
          DELIVERY_TABLE: !Ref DeliveryTable
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:PartiQLSelect
              - dynamodb:PartiQLInsert
              - dynamodb:PartiQLUpdate
              - dynamodb:PartiQLDelete
            Resource: !GetAtt DeliveryTable.Arn
          - Effect: Allow
            Action:
              - geo:SearchPlaceIndexForText
            Resource: !GetAtt MyPlaceIndex.Arn
          - Effect: Allow
            Action:
              - geo:CalculateRoute 
            Resource: !GetAtt MyRouteCalculator.Arn
      Events:
        DeliveryGet:
          Type: HttpApi
          Properties:
            Path: /delivery/{action}/{customerId}/{orderId}
            Method: GET
        DeliveryGetWithAddress:
          Type: HttpApi
          Properties:
            Path: /delivery/{action}/{customerId}/{orderId}/{address}
            Method: GET
        DeliveryGetEstimate:
          Type: HttpApi
          Properties:
            Path: /delivery/{action}/{address}
            Method: GET

  # Order

  OrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Environment:
        Variables:
          ORDER_TABLE: !Ref OrderTable
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - dynamodb:PartiQLSelect
            Resource: !GetAtt OrderTable.Arn
      Events:
        OrderGet:
          Type: HttpApi
          Properties:
            Path: /order/{action}/{customerId}/{orderId}
            Method: GET
        OrderPost:
          Type: HttpApi
          Properties:
            Path: /order/{action}
            Method: POST

  CreateOrderWorkflow:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: create-order/create-order.asl.json
      DefinitionSubstitutions:
        ServerlessHttpApiId: !Sub ${ServerlessHttpApi}
        AWSRegion: !Sub ${AWS::Region}
        OrderTable: !Ref OrderTable
        AddFunctionArn: !GetAtt AddFunction.Arn
      Type: STANDARD
      Policies:
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            Resource:
            - !GetAtt OrderTable.Arn
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - !GetAtt AddFunction.Arn
            - !Sub ${AddFunction.Arn}:*
      Events:
        CreateOrder:
          Type: Api
          Properties:
            Path: /order
            Method: POST

  # Utility Functions
          
  AddFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x

Outputs:

  InventoryTable:
    Description: "Inventory Table"
    Value: !Ref InventoryTable
  InventoryApi:
    Description: "API Gateway endpoint URL for Prod stage for Inventory function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/inventory/{action}/{itemId}"

  PaymentTable:
    Description: "Payment Table"
    Value: !Ref PaymentTable
  PaymentApi:
    Description: "API Gateway endpoint URL for Prod stage for Payment function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/payment/{action}/{what}"

  CustomerTable:
    Description: "Customer Table"
    Value: !Ref CustomerTable
  CustomerApi:
    Description: "API Gateway endpoint URL for Prod stage for Customer function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/customer/{action}/{customerId}"

  DeliveryTable:
    Description: "Delivery Table"
    Value: !Ref DeliveryTable
  DeliveryApi:
    Description: "API Gateway endpoint URL for Prod stage for Delivery function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/delivery"

  OrderTable:
    Description: "Order Table"
    Value: !Ref OrderTable
  DescribeOrderApi:
    Description: "API Gateway endpoint URL for Prod stage for Delivery function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/order"
  CreateOrderApi:
    Description: "API Gateway endpoint URL for Prod stage for Order workflow"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order"

